"""Add scraping fields to ProductRetailer model

Revision ID: 22f47bcb3b4d
Revises: 
Create Date: 2025-07-26 04:06:59.066834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f47bcb3b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_retailers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scrape_attempt', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('scraping_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scrape_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_scrapable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_retailers', schema=None) as batch_op:
        batch_op.drop_column('is_scrapable')
        batch_op.drop_column('scrape_count')
        batch_op.drop_column('scraping_error')
        batch_op.drop_column('last_scrape_attempt')

    # ### end Alembic commands ###
